application: solpowerwebsite
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /images
  static_dir: images
  
- url: /css
  static_dir: css
  
- url: /scripts
  static_dir: scripts

- url: /.*
  script: solpowerwebsite.app
  
libraries:
- name: jinja2
  version: latest